[workspace]
resolver = "3"
members = ["day1", "day2", "day3", "day4", "util"]

[workspace.dependencies]
anyhow = "1.0.100"
thiserror = "2.0.17"
tracing = "0.1.43"
tracing-subscriber = "0.3"

util = { path = "util" }
