[package]
name = "day1-2"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
day1-1 = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
